(use /spork/declare-cc)
(use /spork/build-rules)
(def e (curenv))
(dofile "project.janet" :env e)
(defn install [manifest &]
  (setdyn :verbose true)
  (setdyn *install-manifest* manifest)
  (build-run e "install"))
(defn build [&] (build-run e "build"))
(defn check [&] (build-run e "test"))
(defn clean [&] (build-run e "clean"))
